2020-07-11 10:24:40,295 ERROR: Exception on /reset_password_request [POST] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 93, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\templates\email\reset_password.html", line 8, in template
    <p>Alternatively, your can paster the following link in your browser's address bar:</p>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 's'
2020-07-11 10:26:51,773 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 10:27:06,728 ERROR: Exception on /reset_password_request [POST] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 93, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\templates\email\reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reser_password', token=token, _external=True) }}</p>
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reser_password' with values ['token']. Did you mean 'reset_password' instead?
2020-07-11 10:28:01,676 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 10:28:27,651 ERROR: Exception on /reset_password_request [POST] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 93, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\email.py", line 26, in send_password_reset_email
    user=user, token=token))
TypeError: send_email() got an unexpected keyword argument 'sender'
2020-07-11 10:29:18,220 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:47]
2020-07-11 10:29:44,522 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTk0NDc4MzY4LjI5Mzg3MDd9.YWLvQyijiO4sclnD8zQ-Dv1XJc8u-7r6EDRSVZWF7h4 [GET] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 102, in reset_password
    user = User.verify_reset_passord_token(token)
AttributeError: type object 'User' has no attribute 'verify_reset_passord_token'
