2020-05-17 17:12:31,593 ERROR: Exception on /index [GET] [in c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\routes.py", line 23, in index
    return render_template('index.html', title="Home Page", form=form, posts=posts)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jcumm\documents\12-microblog\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jcumm\Documents\12-microblog\microblog\app\templates\index.html", line 25, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endfor'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-05-17 17:13:44,694 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
2020-05-17 17:17:40,639 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
2020-05-17 17:29:12,245 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
2020-05-17 17:41:06,827 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
2020-05-17 17:51:34,701 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
2020-05-17 17:58:23,341 INFO: Microblog startup [in C:\Users\jcumm\Documents\12-microblog\microblog\app\__init__.py:45]
